config {
    type: "table",
    schema: "consumer_layer",
    name: "tb_dados_finais",
    description: "Tabelas contendo dados climaticos e das distribuidoras em 2023 e 2024",
    columns: {}
}

SELECT
  d.*
  , c.temperature
  , c.precipitation
  , c.flag_precipitation
  , c.humidity
  , c.wind
FROM
  consumer_layer.tb_dados_distribuidora d
LEFT JOIN
  consumer_layer.tb_dados_climaticos c
ON
  c.data_observacao = CAST(d.InicioOcorrencia AS date)
  AND c.distribuidora = d.distribuidora