config {
    type: "table",
    tags: ["ocs"],
    schema: "consumer_layer",
    name: "tb_ocorrencias",
    description: "Tabelas de ocorrencias da Neo com dados tratados",
    columns: {
    },
    bigquery: {
        partitionBy: "CAST(DatGeracaoConjuntoDados AS DATE)"
    },
    assertions: {
        uniqueKey: ["NumOcorrencia"]
    }
}

SELECT 
    *
FROM 
    ${ref("mvw_ocorrencias")}
LIMIT 
    10