/* ('COMPANHIA DE ELETRICIDADE DO ESTADO DA BAHIA COELBA',
    'COMPANHIA ENERGETICA DE PERNAMBUCO',
    'COMPANHIA ENERGÉTICA DE PERNAMBUCO',
    'COMPANHIA ENERGÉTICA DO RIO GRANDE DO NORTE COSERN',
    'ELEKTRO REDES S.A.',
    'NEOENERGIA DISTRIBUICAO BRASILIA S.A.',
    'NEOENERGIA DISTRIBUI�ÃO BRASÍLIA S.A.')*/